name: Macaulay2 tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/macaulay2/testbot:latest
      volumes:
        - ${{ github.workspace }}:/home/macaulay

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Macaulay2 version
        run: M2 --version
      
      - name: Show loaded packages
        run: M2 -e 'print loadedPackages'
      
      - name: random element
        run: M2 -e 'print help randomElement'

      - name: Install package and run tests
        run: M2 --script tests/ci.m2
